theme = "varua"

[editor]
true-color=true
path-completion=false

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-signature-help-docs = false

[editor.inline-diagnostics]
cursor-line = "hint"
